### ISSUE TITLE
npm install有报错，请问可以帮忙解答一下吗？

### ISSUE THREAD

**Issue by 18617201795** [songwonderful/blog-website#11]
![image](https://user-images.githubusercontent.com/57710492/132195365-93717aa1-0f6b-49df-8d48-6d4d7c2b0948.png)

**Comment by songquanpeng** [comment]
这是因为里面依赖了 SQLite，`npm install` 的时候需要编译，编译时需要 Python，这种情况下你需要安装 Python。

我之前没注意到是因为我本地和服务器都是有 Python 环境的。
